name: Build DevOps Toolkit Images
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/builder.yaml"

  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/builder.yaml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: check filters
        uses: dorny/paths-filter@v2
        id: filter
        with:
          base: main
          filters: |
            core-1804:
              - 'src/*/ubuntu.1804/**'
            core-2004:
              - 'src/*/ubuntu.2004/**'

      - name: Ubuntu 18.04 builder
        if: steps.filter.outputs.core1804 == 'true'
        runs-on: ubuntu-latest
        steps:
          - name: Build Image
            uses: docker/build-push-action@v2
            with:
              path: ./src/ansible/ubuntu18.04
              push: false
              tags: kevinedwards/devops-toolkit:ubuntu18.04

      - name: ubuntu 20.04 builder
        if: steps.filter.outputs.core2004 == 'true'
        runs-on: ubuntu-latest
        steps:
          - name: Build Image
            uses: docker/build-push-action@v2
            with:
              path: ./src/ansible/ubuntu20.04
              push: false
              tags: kevinedwards/devops-toolkit:ubuntu20.04

  #   name: check modified images
  #   runs-on: ubuntu-latest
  #     - name: check modified files
  #       id: check_files
  #       run: |
  #         git diff --name-status main > files.txt
  #         while IFS= read -r file
  #         do
  #           if [[ $file = src/* ]]; then
  #             echo "::set-output name=run_$(basename $(realpath "${file%/*}"))::true"
  #           fi
  #         done < files.txt
  # build:
  #   name: build images
  #   needs: check_image
  #   if: needs.check_image.outputs.run_ubuntu18.04 == 'true'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Build Image
  #       uses: docker/build-push-action@v2
  #       with:
  #         path: ./src/ansible/ubuntu18.04
  #         push: false
  #         tags: kevinedwards/devops-toolkit:ubuntu18.04