name: Build DevOps Toolkit Images
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/builder.yaml"

  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/builder.yaml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: check filters
        uses: dorny/paths-filter@v2
        id: filter
        with:
          base: main
          filters: |
            1804:
              - 'src/ansible/ubuntu18.04/**'
            2004:
              - 'src/ansible/ubuntu20.04/**'
            core-1804:
              - 'src/ansible-core/ubuntu18.04/**'
            core-2004:
              - 'src/ansible-core/ubuntu20.04/**'

      - name: Ubuntu 18.04 builder
        if: steps.filter.outputs.1804 == 'true'
        runs-on: ubuntu-latest
        steps:
          - name: Build Image
            uses: docker/build-push-action@v2
            with:
              path: ./src/ansible/ubuntu18.04
              push: false
              tags: kevinedwards/devops-toolkit:ubuntu18.04

      - name: ubuntu 20.04 builder
        if: steps.filter.outputs.2004 == 'true'
        runs-on: ubuntu-latest
        steps:
          - name: Build Image
            uses: docker/build-push-action@v2
            with:
              path: ./src/ansible/ubuntu20.04
              push: false
              tags: kevinedwards/devops-toolkit:ubuntu20.04

      - name: Ubuntu 18.04 - Core builder
        if: steps.filter.outputs.core-1804 == 'true'
        runs-on: ubuntu-latest
        steps:
          - name: Build Image
            uses: docker/build-push-action@v2
            with:
              path: ./src/ansible-core/ubuntu18.04
              push: false
              tags: kevinedwards/devops-toolkit:ubuntu18.04c

      - name: ubuntu 20.04 Core builder
        if: steps.filter.outputs.core-2004 == 'true'
        runs-on: ubuntu-latest
        steps:
          - name: Build Image
            uses: docker/build-push-action@v2
            with:
              path: ./src/ansible-core/ubuntu20.04
              push: false
              tags: kevinedwards/devops-toolkit:ubuntu20.04c