name: Build DevOps Toolkit Images
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/builder.yaml"

  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/builder.yaml"
jobs:
  tester:
    runs-on: ubuntu-latest
    outputs:
      ubuntu_base_1804: ${{ steps.test_ubuntu_base_1804.outputs.changed}}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: check filters
        uses: dorny/paths-filter@v2
        id: filter
        with:
          base: main
          filters: |
            ubuntu_base_1804:
              - 'src/ansible/ubuntu18.04/**'
            ubuntu_base_2004:
              - 'src/ansible/ubuntu20.04/**'
            ubuntu_core_1804:
              - 'src/ansible-core/ubuntu18.04/**'
            ubuntu_core_2004:
              - 'src/ansible-core/ubuntu20.04/**'

      - name: Ubuntu 18.04 Base Test
        id: test_ubuntu_base_1804
        if: steps.filter.outputs.ubuntu_base_1804 == 'true'
        run: |
          echo ::set-output name=changed::true

  ubuntu_base_1804:
    runs-on: ubuntu-latest
    needs: tester
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: checkout repository
        uses: actions/checkout@v3.0.0

      - name: Ubuntu 18.04 Builder
        uses: docker/build-push-action@v2.8.0
        with:
          context: src/ansible/ubuntu18.04
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-toolkit:ansible18.04