name: Build DevOps Toolkit Images
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/builder.yaml"

  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/builder.yaml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: check filters
        uses: dorny/paths-filter@v2
        id: filter
        with:
          base: main
          filters: |
            a1804:
              - 'src/ansible/ubuntu18.04/**'
            a2004:
              - 'src/ansible/ubuntu20.04/**'
            ac1804:
              - 'src/ansible-core/ubuntu18.04/**'
            ac2004:
              - 'src/ansible-core/ubuntu20.04/**'

      - name: Ubuntu 18.04 builder
        if: steps.filter.outputs.a1804 == 'true'
        uses: docker/build-push-action@v2
        with:
          path: ./src/ansible/ubuntu18.04
          push: true
          tags: kevinedwards/devops-toolkit:18

      - name: ubuntu 20.04 builder
        if: steps.filter.outputs.a2004 == 'true'
        uses: docker/build-push-action@v2
        with:
          path: ./src/ansible/ubuntu20.04
          push: true
          tags: kevinedwards/devops-toolkit:20

      - name: Ubuntu 18.04 - Core builder
        if: steps.filter.outputs.ac1804 == 'true'
        uses: docker/build-push-action@v2
        with:
          path: ./src/ansible-core/ubuntu18.04
          push: true
          tags: kevinedwards/devops-toolkit:core18

      - name: ubuntu 20.04 Core builder
        if: steps.filter.outputs.ac2004 == 'true'
        uses: docker/build-push-action@v2
        with:
          path: ./src/ansible-core/ubuntu20.04
          push: true
          tags: kevinedwards/devops-toolkit:core20